### ISSUE TITLE
Issue?? "write response"...?

### ISSUE THREAD

**Issue by luissimoes** [bombadiltom/homebridge-rademacher-homepilot#84] opened 2021-02-20 21:12 UTC
I have this error now...

<<
[homebridge-rademacher-homepilot] This plugin generated a warning from the characteristic 'Target Position': SET handler returned write response value, though the characteristic doesn't support write response! See https://git.io/JtMGR for more info.
>>

sorry.. no idea what this means but am getting this

**Comment by FlasSh21** [comment] 2021-02-20 21:22
I have the same issue

**Comment by Boehmer86** [comment] 2021-02-21 20:42
This looks like a duplicate of #83 – to confirm, you all upgraded to Homebridge 1.3.x, correct?

Best

Robert

**Comment by luissimoes** [comment] 2021-02-21 21:25
> This looks like a duplicate of #83 – to confirm, you all upgraded to Homebridge 1.3.x, correct?
> 
> Best
> 
> Robert

yep... I am on 1.3.0

**Closed** 2021-02-23 08:52 UTC
